@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueClassTagList
UniqueClassTagList -[hidden]down- UniquePersonList
UniqueClassTagList -[hidden]down- UniquePersonList

UniqueClassTagList -right-> "*" ClassTag
UniquePersonList -right-> Person

Person -up-> "*" ClassTag

Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
@enduml
